version: '1.0'
services:

  webpoint-assignment-rabigorkhali-container:
    container_name: webpoint-assignment-rabigorkhali-container
    build: . 
    volumes:
      - ./application-files:/var/www/html
    ports:
      - 9002:80
  
  mysql_db:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webpoint_assignment_rabigorkhali_db
    ports:
    - 3306:3306
  
  phpmyadmin: 
    image: phpmyadmin:5.2.1
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1